// Contoh data default untuk struktur organisasi dan publikasi
// File ini bisa digunakan sebagai referensi atau untuk reset data

export const exampleMembers = [
  {
    id: "1",
    name: "Tia Rahmania, M.Psi, Psikologi",
    position: "KETUA",
    education: "M.Psi",
    level: 1,
    department: "Leadership",
    order: 1,
  },
  {
    id: "2",
    name: "Muhammad Zakaria, S.Pd",
    position: "SEKRETARIS",
    education: "S.Pd",
    level: 1,
    department: "Leadership",
    order: 2,
  },
  {
    id: "3",
    name: "Zaidra Birru Burlian, S.Sos",
    position: "RISET PENGEMBANGAN",
    education: "S.Sos",
    level: 2,
    department: "Research",
    order: 3,
  },
  {
    id: "4",
    name: "Wilna Liana Azzahira",
    position: "SOSIALISASI DAN EDUKASI",
    education: "S.Pd",
    level: 2,
    department: "Education",
    order: 4,
  },
  {
    id: "5",
    name: "Fitri Aiyah Mahdiyah",
    position: "PELAPORAN DAN PENCADUAN KASUS",
    education: "S.H",
    level: 2,
    department: "Case Management",
    order: 5,
  },
  {
    id: "6",
    name: "Heni Dwi Febrianti, S.Pd",
    position: "PELAPORAN DAN PENCADUAN KASUS",
    education: "S.Pd",
    level: 2,
    department: "Case Management",
    order: 6,
  },
  {
    id: "7",
    name: "Fitri Aiyah Mahdiyah",
    position: "REHABILITAS",
    education: "S.Psi",
    level: 3,
    department: "Rehabilitation",
    order: 7,
  },
  {
    id: "8",
    name: "Dr. Muhammad Sidiq",
    position: "PENANGANAN KASUS",
    education: "Dr.",
    level: 3,
    department: "Case Handling",
    order: 8,
  },
  {
    id: "9",
    name: "Aliq Rahmautillah, M.Sos",
    position: "PENANGANAN KASUS",
    education: "M.Sos",
    level: 3,
    department: "Case Handling",
    order: 9,
  },
  {
    id: "10",
    name: "Fushi Nur Sabrina",
    position: "RISET DAN PENGEMBANGAN",
    education: "S.Psi",
    level: 3,
    department: "Research",
    order: 10,
  },
];

export const examplePublications = [
  {
    id: "1",
    title: "Protokol Penanganan Kekerasan Berbasis Gender",
    category: "tulisan" as const,
    author: "Tim PPKPT",
    description:
      "Panduan komprehensif untuk penanganan kasus kekerasan berbasis gender di institusi pendidikan",
    link: "https://example.com/protokol",
    date: "2025-01-15",
    order: 1,
  },
  {
    id: "2",
    title: "Laporan Aktivitas PPKPT Semester I 2024",
    category: "laporan" as const,
    author: "Tia Rahmania",
    description:
      "Laporan komprehensif tentang kegiatan dan capaian PPKPT selama semester pertama tahun 2024",
    link: "https://example.com/laporan-2024-1",
    date: "2024-06-30",
    order: 1,
  },
  {
    id: "3",
    title: "Edukasi Pencegahan Kekerasan di Kampus",
    category: "tulisan" as const,
    author: "Wilna Liana Azzahira",
    description:
      "Materi edukasi untuk meningkatkan kesadaran mahasiswa tentang pencegahan kekerasan",
    link: "https://example.com/edukasi",
    date: "2025-01-10",
    order: 2,
  },
  {
    id: "4",
    title: "Laporan Evaluasi Program Sosialisasi 2024",
    category: "laporan" as const,
    author: "Fitri Aiyah Mahdiyah",
    description:
      "Evaluasi lengkap terhadap program sosialisasi dan dampaknya bagi masyarakat kampus",
    link: "https://example.com/eval-2024",
    date: "2024-12-15",
    order: 2,
  },
  {
    id: "5",
    title: "Panduan Pelaporan Kasus untuk Korban Kekerasan",
    category: "tulisan" as const,
    author: "Heni Dwi Febrianti",
    description:
      "Petunjuk langkah demi langkah bagi korban kekerasan dalam melaporkan kasusnya",
    date: "2025-01-05",
    order: 3,
  },
];
